spring:
  application:
    name: billing-invoice

  cloud:
    config:
      enabled: false

  datasource:
    url: jdbc:postgresql://149.56.107.189:5432/db_formation
    username: root
    password: eSFHR9u2mbBVLLDJtSG3
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    schemas: invoice
    default-schema: invoice
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/billing

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

camel:
  dataformat:
    jackson:
      auto-discover-object-mapper: true

billing:
  rabbitmq:
    exchange: billing.exchange
    payment-requested-queue: payment.requested.queue
    payment-completed-queue: invoice.payment.completed.queue
    payment-requested-routing-key: payment.requested
    payment-completed-routing-key: payment.completed
